# Generated by Django 2.1.4 on 2020-03-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200317_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=255),
        ),
    ]
