# Generated by Django 2.1.4 on 2020-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20200317_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='deactive', max_length=255),
        ),
    ]
